-- require("code_runner").setup({
-- 	mode = "toggleterm",
-- 	startinsert = true,
-- 	-- term = {
-- 	-- 	--  Position to open the terminal, this option is ignored if mode ~= term
-- 	-- 	position = "bot",
-- 	-- 	-- window size, this option is ignored if tab is true
-- 	-- 	size = 8,
-- 	-- },
-- 	filetype = {
-- 		-- java = {
-- 		--   "cd $dir &&",
-- 		--   "javac $fileName &&",
-- 		--   "java $fileNameWithoutExt"
-- 		-- },
-- 		python = "python3 -u",
-- 		typescript = "deno run",
-- 		rust = {
-- 			"cd $dir &&",
-- 			"rustc $fileName &&",
-- 			"$dir/$fileNameWithoutExt",
-- 		},
-- 		cpp = {
-- 			"g++ $dir/$fileName -o $dir/$fileNameWithoutExt &&",
-- 			"$dir/$fileNameWithoutExt && rm $dir/$fileNameWithoutExt",
-- 		},
-- 	},
-- })
