# import = ["./ayu_dark.yml"]
[font]
size = 12.0

[font.normal]
family = "Hack"
style = "Regular"

[window]
opacity = 0.97
dynamic_padding = true
#[colors.primary]
#background = "#000000"
#foreground = "#FFFFFF"

[window.padding]
x = 8
y = 3
# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors
[[keyboard.bindings]]
action = 'ToggleFullscreen'
key = 'F11'
[[keyboard.bindings]]
key = 'i'
mods = 'Alt'
mode = '~AppCursor'
chars = '\x1b[H'
[[keyboard.bindings]]
key = 'o'
mods = 'Alt'
mode = '~AppCursor'
chars = '\x1b[F'



# [colors.primary]
# foreground = "#e0def4"
# background = "#232136"
# dim_foreground = "#908caa"
# bright_foreground = "#e0def4"
#
# [colors.cursor]
# text = "#e0def4"
# cursor = "#56526e"
#
# [colors.vi_mode_cursor]
# text = "#e0def4"
# cursor = "#56526e"
#
# [colors.search.matches]
# foreground = "#908caa"
# background = "#393552"
#
# [colors.search.focused_match]
# foreground = "#232136"
# background = "#ea9a97"
#
# [colors.hints.start]
# foreground = "#908caa"
# background = "#2a273f"
#
# [colors.hints.end]
# foreground = "#6e6a86"
# background = "#2a273f"
#
# [colors.line_indicator]
# foreground = "None"
# background = "None"
#
# [colors.footer_bar]
# foreground = "#e0def4"
# background = "#2a273f"
#
# [colors.selection]
# text = "#e0def4"
# background = "#44415a"
#
# [colors.normal]
# black = "#393552"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"
#
# [colors.bright]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"
#
# [colors.dim]
# black = "#6e6a86"
# red = "#eb6f92"
# green = "#3e8fb0"
# yellow = "#f6c177"
# blue = "#9ccfd8"
# magenta = "#c4a7e7"
# cyan = "#ea9a97"
# white = "#e0def4"
#


# Colors (Ayu Dark)
[colors.primary]
  # Default colors
background= '#0A0E14'
foreground= '#B3B1AD'
[colors.normal]
black= '#01060E'
red= '#EA6C73'
green= '#91B362'
yellow= '#F9AF4F'
blue= '#53BDFA'
magenta= '#FAE994'
cyan= '#90E1C6'
white= '#C7C7C7'
[colors.bright]
black= '#686868'
red= '#F07178'
green= '#C2D94C'
yellow= '#FFB454'
blue= '#59C2FF'
magenta= '#FFEE99'
cyan= '#95E6CB'
white= '#FFFFFF'
